import mongoose from "mongoose";
import bcrypt from "bcryptjs";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.resolve(process.cwd(), "backend/.env") });
dotenv.config({ path: path.resolve(process.cwd(), ".env") });
dotenv.config();

import { User } from "../src/models/User.js";
import { Merchant } from "../src/models/Merchant.js";
import { Product } from "../src/models/Product.js";
import { RevenueOpportunity } from "../src/models/RevenueOpportunity.js";

const MONGODB_URI = process.env.MONGODB_URI;

if (!MONGODB_URI) {
  console.error("[SEED ERROR] MONGODB_URI is not defined. Please configure your .env file.");
  process.exit(1);
}

const seedData = async () => {
  try {
    console.log("[SEED] Connecting to MongoDB Atlas...");
    await mongoose.connect(MONGODB_URI);
    console.log("[SEED] Connected successfully. Beginning idempotent seeding...");

    const salt = await bcrypt.genSalt(10);
    const defaultPasswordHash = await bcrypt.hash("password123", salt);
    const defaultPinHash = await bcrypt.hash("1234", salt);

    // 1. Seed Demo Merchant User
    const merchantUser = await User.findOneAndUpdate(
      { email: "merchant@apexnova.store" },
      {
        $setOnInsert: {
          email: "merchant@apexnova.store",
          passwordHash: defaultPasswordHash,
          name: "Apex Nova Store Manager",
          role: "MERCHANT",
          merchantId: "merch_apex_001",
          language: "en",
          spendingControls: {
            autonomousLimit: 10000,
            requirePinAbove: 10000,
            transactionPinHash: defaultPinHash,
            maxDailySpend: 500000,
            spentToday: 0,
            lastSpendReset: new Date(),
          },
        },
      },
      { upsert: true, new: true }
    );

    // 2. Seed Demo Customer User
    await User.findOneAndUpdate(
      { email: "customer@gmail.com" },
      {
        $setOnInsert: {
          email: "customer@gmail.com",
          passwordHash: defaultPasswordHash,
          name: "Rahul Sharma",
          role: "CUSTOMER",
          language: "en",
          spendingControls: {
            autonomousLimit: 2000,
            requirePinAbove: 2000,
            transactionPinHash: defaultPinHash,
            maxDailySpend: 100000,
            spentToday: 0,
            lastSpendReset: new Date(),
          },
          address: {
            street: "42 Residency Road, Ashok Nagar",
            city: "Bengaluru",
            state: "Karnataka",
            postalCode: "560025",
            country: "India",
          },
        },
      },
      { upsert: true, new: true }
    );

    // 3. Seed Merchant Profile
    await Merchant.findOneAndUpdate(
      { merchantId: "merch_apex_001" },
      {
        merchantId: "merch_apex_001",
        businessName: "Apex Nova Lifestyle & Tech",
        category: "Electronics, Lifestyle & Computing",
        gstin: "29AABCU9603R1ZM",
        currency: "INR",
        negotiationPolicy: {
          allowNegotiation: true,
          maxDiscountPercent: 10,
          minMarginThreshold: 500,
        },
        capabilities: [
          "catalog_search",
          "stock_verification",
          "price_verification",
          "bounded_negotiation",
          "order_preparation",
          "cross_sell_recommendations",
          "bundle_promotions",
        ],
        ownerUserId: merchantUser._id,
      },
      { upsert: true }
    );

    const products: any[] = [];
    // Laptops
    products.push(
      {
        productId: "prod_laptop_001",
        merchantId: "merch_apex_001",
        sku: "LEN-IP5-16",
        name: "Lenovo IdeaPad Slim 5 16-inch",
        category: "Laptops",
        subcategory: "Ultrabooks",
        description: "16-inch WUXGA display, Intel Core i5 13th Gen, 16GB LPDDR5 RAM, 512GB NVMe SSD, backlit keyboard, ideal for software engineering and multitasking.",
        price: 64999,
        currency: "INR",
        stock: 14,
        availability: "IN_STOCK",
        rating: 4.6,
        reviewCount: 142,
        specifications: {
          Processor: "Intel Core i5-13500H",
          RAM: "16GB LPDDR5",
          Storage: "512GB NVMe M.2 SSD",
          Display: "16-inch IPS FHD+ (1920x1200)",
        },
        tags: ["laptop", "programming", "intel", "16gb", "ultrabook", "student"],
        discountPercent: 5,
        imageUrl: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_acc_001", "prod_acc_002", "prod_acc_003"],
        frequentlyBoughtTogetherIds: ["prod_acc_001", "prod_acc_002"],
        upsellProductIds: ["prod_laptop_002"],
        alternativeProductIds: ["prod_laptop_003"],
        viewCount: 1240,
        salesCount: 84,
      },
      {
        productId: "prod_laptop_002",
        merchantId: "merch_apex_001",
        sku: "LEN-TP-E14",
        name: "ThinkPad E14 Gen 5 Pro",
        category: "Laptops",
        subcategory: "Business Laptops",
        description: "Military-grade durability, AMD Ryzen 7 7730U, 16GB DDR4, 1TB SSD, legendary ThinkPad keyboard, fingerprint biometric reader.",
        price: 69999,
        currency: "INR",
        stock: 9,
        availability: "IN_STOCK",
        rating: 4.8,
        reviewCount: 98,
        specifications: {
          Processor: "AMD Ryzen 7 7730U (8 cores / 16 threads)",
          RAM: "16GB DDR4 3200MHz",
          Storage: "1TB PCIe NVMe SSD",
        },
        tags: ["laptop", "programming", "thinkpad", "ryzen7", "business", "developer"],
        discountPercent: 0,
        imageUrl: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_acc_001", "prod_acc_002"],
        frequentlyBoughtTogetherIds: ["prod_acc_001"],
        upsellProductIds: ["prod_laptop_004"],
        alternativeProductIds: ["prod_laptop_001"],
        viewCount: 1890,
        salesCount: 122,
      },
      {
        productId: "prod_laptop_003",
        merchantId: "merch_apex_001",
        sku: "ASUS-VIVO-15",
        name: "ASUS Vivobook 15 OLED",
        category: "Laptops",
        subcategory: "Budget Ultrabooks",
        description: "Vibrant 15.6-inch Full HD OLED screen, Intel Core i3 12th Gen, 8GB RAM, 512GB SSD, slim lightweight chassis.",
        price: 43999,
        currency: "INR",
        stock: 18,
        availability: "IN_STOCK",
        rating: 4.4,
        reviewCount: 76,
        specifications: {
          Processor: "Intel Core i3-1215U",
          RAM: "8GB DDR4",
          Storage: "512GB NVMe SSD",
        },
        tags: ["laptop", "budget", "oled", "asus", "students"],
        discountPercent: 8,
        imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_acc_001", "prod_acc_002"],
        frequentlyBoughtTogetherIds: ["prod_acc_001"],
        upsellProductIds: ["prod_laptop_001"],
        alternativeProductIds: ["prod_laptop_001"],
        viewCount: 940,
        salesCount: 65,
      },
      {
        productId: "prod_laptop_004",
        merchantId: "merch_apex_001",
        sku: "ASUS-ROG-G16",
        name: "ASUS ROG Strix G16 Gaming Laptop",
        category: "Laptops",
        subcategory: "Gaming",
        description: "13th Gen Intel Core i7-13650HX, NVIDIA GeForce RTX 4060 8GB GDDR6, 16GB DDR5 4800MHz, 1TB PCIe 4.0 SSD, 165Hz FHD+ display.",
        price: 114999,
        currency: "INR",
        stock: 6,
        availability: "IN_STOCK",
        rating: 4.9,
        reviewCount: 115,
        specifications: {
          Processor: "Intel Core i7-13650HX",
          Graphics: "NVIDIA GeForce RTX 4060 8GB",
          RAM: "16GB DDR5",
        },
        tags: ["laptop", "gaming", "rtx4060", "rog", "high-performance"],
        discountPercent: 4,
        imageUrl: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_acc_001", "prod_gaming_001", "prod_audio_003"],
        frequentlyBoughtTogetherIds: ["prod_gaming_001", "prod_audio_003"],
        upsellProductIds: [],
        alternativeProductIds: ["prod_laptop_002"],
        viewCount: 3120,
        salesCount: 145,
      }
    );
    // Phones
    products.push(
      {
        productId: "prod_phone_001",
        merchantId: "merch_apex_001",
        sku: "GOOG-PIX-8A",
        name: "Google Pixel 8a 5G",
        category: "Phones",
        subcategory: "Smartphones",
        description: "Google Tensor G3 chip, industry-leading AI camera with Best Take & Magic Editor, 64MP dual rear camera, 120Hz Actua display, 7 years of OS updates.",
        price: 37999,
        currency: "INR",
        stock: 22,
        availability: "IN_STOCK",
        rating: 4.7,
        reviewCount: 310,
        specifications: {
          Camera: "64MP Quad PD wide + 13MP ultrawide",
          Processor: "Google Tensor G3",
          Display: "6.1-inch 120Hz OLED",
        },
        tags: ["phone", "smartphone", "camera", "pixel", "5g", "ai-camera"],
        discountPercent: 10,
        imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_phone_acc_001", "prod_phone_acc_002", "prod_audio_002"],
        frequentlyBoughtTogetherIds: ["prod_phone_acc_001", "prod_phone_acc_002"],
        upsellProductIds: ["prod_phone_002"],
        alternativeProductIds: ["prod_phone_003"],
        viewCount: 4200,
        salesCount: 320,
      },
      {
        productId: "prod_phone_002",
        merchantId: "merch_apex_001",
        sku: "SAMS-S24-FE",
        name: "Samsung Galaxy S24 FE",
        category: "Phones",
        subcategory: "Flagship",
        description: "Galaxy AI features, 50MP ProVisual Engine camera, Exynos 2400e, 6.7-inch Dynamic AMOLED 2X 120Hz, premium aluminum frame.",
        price: 54999,
        currency: "INR",
        stock: 15,
        availability: "IN_STOCK",
        rating: 4.6,
        reviewCount: 180,
        specifications: {
          Camera: "50MP Wide + 12MP Ultra-wide + 8MP 3x Telephoto",
          Display: "6.7-inch Dynamic AMOLED 2X",
        },
        tags: ["phone", "smartphone", "samsung", "camera", "flagship", "galaxy-ai"],
        discountPercent: 5,
        imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_phone_acc_001", "prod_phone_acc_002", "prod_audio_002"],
        frequentlyBoughtTogetherIds: ["prod_phone_acc_001"],
        upsellProductIds: [],
        alternativeProductIds: ["prod_phone_001"],
        viewCount: 2600,
        salesCount: 190,
      },
      {
        productId: "prod_phone_003",
        merchantId: "merch_apex_001",
        sku: "OP-12R-5G",
        name: "OnePlus 12R 5G",
        category: "Phones",
        subcategory: "Performance",
        description: "Snapdragon 8 Gen 2, 5500mAh battery with 100W SUPERVOOC charging, 4th Gen LTPO 120Hz ProXDR display, 50MP Sony IMX890 camera.",
        price: 29999,
        currency: "INR",
        stock: 25,
        availability: "IN_STOCK",
        rating: 4.6,
        reviewCount: 420,
        specifications: {
          Camera: "50MP Sony IMX890 OIS",
          Processor: "Qualcomm Snapdragon 8 Gen 2",
          Battery: "5500mAh 100W SuperVOOC",
        },
        tags: ["phone", "smartphone", "oneplus", "fast-charging", "under-30000", "camera"],
        discountPercent: 0,
        imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_phone_acc_001", "prod_phone_acc_002", "prod_audio_002"],
        frequentlyBoughtTogetherIds: ["prod_phone_acc_001", "prod_audio_002"],
        upsellProductIds: ["prod_phone_001"],
        alternativeProductIds: ["prod_phone_001"],
        viewCount: 5100,
        salesCount: 410,
      }
    );
    // Headphones & Audio
    products.push(
      {
        productId: "prod_audio_001",
        merchantId: "merch_apex_001",
        sku: "SONY-WH1000-XM5",
        name: "Sony WH-1000XM5 Wireless ANC Headphones",
        category: "Headphones",
        subcategory: "Over-Ear",
        description: "Industry-leading noise cancellation with 8 microphones, Auto NC Optimizer, 30-hour battery life, speak-to-chat, ultra-comfortable lightweight design.",
        price: 26999,
        currency: "INR",
        stock: 12,
        availability: "IN_STOCK",
        rating: 4.8,
        reviewCount: 540,
        specifications: {
          Type: "Wireless Over-Ear ANC",
          BatteryLife: "30 hours (ANC on)",
          Connectivity: "Bluetooth 5.2 Multipoint, LDAC",
        },
        tags: ["headphones", "audio", "sony", "anc", "noise-cancelling", "music"],
        discountPercent: 7,
        imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_laptop_001", "prod_phone_001"],
        frequentlyBoughtTogetherIds: [],
        upsellProductIds: [],
        alternativeProductIds: ["prod_audio_002"],
        viewCount: 3800,
        salesCount: 290,
      },
      {
        productId: "prod_audio_002",
        merchantId: "merch_apex_001",
        sku: "OP-BUDS-PRO2",
        name: "OnePlus Buds Pro 2 True Wireless",
        category: "Headphones",
        subcategory: "In-Ear TWS",
        description: "MelodyBoost Dual Drivers co-created with Dynaudio, 48dB adaptive smart noise cancellation, spatial audio, up to 39 hours playback.",
        price: 8999,
        currency: "INR",
        stock: 30,
        availability: "IN_STOCK",
        rating: 4.5,
        reviewCount: 220,
        specifications: {
          Type: "True Wireless Earbuds (In-Ear)",
          BatteryLife: "39 hours with case",
          ANC: "48dB Smart Adaptive",
        },
        tags: ["earbuds", "audio", "tws", "oneplus", "anc", "wireless"],
        discountPercent: 12,
        imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_phone_001", "prod_phone_003"],
        frequentlyBoughtTogetherIds: ["prod_phone_003"],
        upsellProductIds: ["prod_audio_001"],
        alternativeProductIds: ["prod_audio_001"],
        viewCount: 2100,
        salesCount: 180,
      },
      {
        productId: "prod_audio_003",
        merchantId: "merch_apex_001",
        sku: "HPX-CLOUD-3",
        name: "HyperX Cloud III Gaming Headset",
        category: "Headphones",
        subcategory: "Gaming Headset",
        description: "Re-engineered angled 53mm drivers, DTS Headphone:X Spatial Audio, ultra-clear 10mm noise-cancelling microphone with LED mute indicator.",
        price: 6499,
        currency: "INR",
        stock: 19,
        availability: "IN_STOCK",
        rating: 4.6,
        reviewCount: 175,
        specifications: {
          Drivers: "53mm Neodymium",
          Microphone: "10mm Detachable Noise-canceling",
        },
        tags: ["gaming", "headset", "audio", "hyperx", "accessories"],
        discountPercent: 5,
        imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_laptop_004", "prod_gaming_001"],
        frequentlyBoughtTogetherIds: ["prod_gaming_001"],
        upsellProductIds: ["prod_audio_001"],
        alternativeProductIds: [],
        viewCount: 1450,
        salesCount: 110,
      }
    );
    // Accessories
    products.push(
      {
        productId: "prod_acc_001",
        merchantId: "merch_apex_001",
        sku: "LOGI-MX-M3S",
        name: "Logitech MX Master 3S Wireless Mouse",
        category: "Accessories",
        subcategory: "Mice",
        description: "Quiet Clicks, 8K DPI track-on-glass sensor, MagSpeed electromagnetic scrolling, ergonomic thumb rest, connects up to 3 devices across Mac and Windows.",
        price: 7995,
        currency: "INR",
        stock: 35,
        availability: "IN_STOCK",
        rating: 4.9,
        reviewCount: 880,
        specifications: {
          Sensor: "8000 DPI Darkfield High Precision",
          Buttons: "7 Customizable Action Buttons",
          Battery: "Up to 70 days rechargeable USB-C",
        },
        tags: ["mouse", "logitech", "accessories", "productivity", "developer", "ergonomic"],
        discountPercent: 0,
        imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_laptop_001", "prod_laptop_002", "prod_laptop_004"],
        frequentlyBoughtTogetherIds: ["prod_laptop_001", "prod_acc_002"],
        upsellProductIds: [],
        alternativeProductIds: ["prod_gaming_001"],
        viewCount: 4900,
        salesCount: 610,
      },
      {
        productId: "prod_acc_002",
        merchantId: "merch_apex_001",
        sku: "MOK-BAG-16",
        name: "Mokobara The Transit Backpack (16L Water-Resistant)",
        category: "Accessories",
        subcategory: "Bags & Sleeves",
        description: "Crafted with vegan leather and water-resistant nylon, dedicated padded compartment for 16-inch laptops, luggage pass-through sleeve, hidden anti-theft pocket.",
        price: 3499,
        currency: "INR",
        stock: 28,
        availability: "IN_STOCK",
        rating: 4.7,
        reviewCount: 310,
        specifications: {
          Capacity: "16 Litres",
          LaptopFit: "Up to 16.2-inch Laptops",
        },
        tags: ["bag", "laptop-bag", "backpack", "travel", "accessories"],
        discountPercent: 15,
        imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_laptop_001", "prod_laptop_002", "prod_laptop_003"],
        frequentlyBoughtTogetherIds: ["prod_laptop_001", "prod_acc_001"],
        upsellProductIds: [],
        alternativeProductIds: [],
        viewCount: 2200,
        salesCount: 240,
      },
      {
        productId: "prod_acc_003",
        merchantId: "merch_apex_001",
        sku: "PORT-COOL-X",
        name: "Portronics My Buddy K9 Ergonomic Laptop Stand with Cooling Pad",
        category: "Accessories",
        subcategory: "Stands & Cooling",
        description: "Heavy-duty aluminum alloy construction, 7 adjustable height angles, dual high-speed silent fans with blue LED illumination, non-slip silicone pads.",
        price: 1499,
        currency: "INR",
        stock: 45,
        availability: "IN_STOCK",
        rating: 4.4,
        reviewCount: 160,
        specifications: {
          Material: "Sandblasted Aluminum Alloy",
          Cooling: "Dual 120mm Silent USB-powered fans",
        },
        tags: ["cooling-pad", "laptop-stand", "accessories", "ergonomics"],
        discountPercent: 10,
        imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_laptop_001", "prod_laptop_002", "prod_laptop_004"],
        frequentlyBoughtTogetherIds: ["prod_laptop_001"],
        upsellProductIds: [],
        alternativeProductIds: [],
        viewCount: 1300,
        salesCount: 190,
      },
      {
        productId: "prod_gaming_001",
        merchantId: "merch_apex_001",
        sku: "RAZ-DEATH-V3",
        name: "Razer DeathAdder V3 Pro Gaming Mouse",
        category: "Gaming",
        subcategory: "Gaming Mice",
        description: "Ultra-lightweight 63g ergonomic design, Focus Pro 30K Optical Sensor, Optical Mouse Switches Gen-3 with zero double-clicking, 90 hours battery life.",
        price: 10999,
        currency: "INR",
        stock: 14,
        availability: "IN_STOCK",
        rating: 4.8,
        reviewCount: 290,
        specifications: {
          Weight: "63 grams ultra-light",
          Sensor: "30,000 DPI Optical",
        },
        tags: ["gaming", "mouse", "razer", "esports", "wireless"],
        discountPercent: 8,
        imageUrl: "https://images.unsplash.com/photo-1626880019808-8e6848037d03?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_laptop_004", "prod_audio_003"],
        frequentlyBoughtTogetherIds: ["prod_audio_003", "prod_laptop_004"],
        upsellProductIds: [],
        alternativeProductIds: ["prod_acc_001"],
        viewCount: 2700,
        salesCount: 170,
      },
      {
        productId: "prod_phone_acc_001",
        merchantId: "merch_apex_001",
        sku: "SPIG-CASE-PX8A",
        name: "Spigen Rugged Armor Matte Shockproof Case",
        category: "Accessories",
        subcategory: "Phone Cases",
        description: "Carbon fiber accents with Air Cushion Technology for certified military-grade drop protection, tactile button covers, raised lips to protect screen and camera.",
        price: 999,
        currency: "INR",
        stock: 60,
        availability: "IN_STOCK",
        rating: 4.8,
        reviewCount: 450,
        specifications: {
          Protection: "Air Cushion Military Drop-Tested",
          Finish: "Matte Black TPU",
        },
        tags: ["phone-case", "spigen", "accessories", "protection"],
        discountPercent: 0,
        imageUrl: "https://images.unsplash.com/photo-1601593346740-925612772716?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_phone_001"],
        frequentlyBoughtTogetherIds: ["prod_phone_001", "prod_phone_acc_002"],
        upsellProductIds: [],
        alternativeProductIds: [],
        viewCount: 1600,
        salesCount: 380,
      },
      {
        productId: "prod_phone_acc_002",
        merchantId: "merch_apex_001",
        sku: "ANK-65W-GAN",
        name: "Anker Prime 67W GaN Wall Fast Charger (3 Ports)",
        category: "Accessories",
        subcategory: "Chargers",
        description: "Ultra-compact Gallium Nitride fast charger with 2 USB-C and 1 USB-A ports, ActiveShield 2.0 safety temperature monitoring, fast charges laptops and phones.",
        price: 2999,
        currency: "INR",
        stock: 35,
        availability: "IN_STOCK",
        rating: 4.9,
        reviewCount: 390,
        specifications: {
          PowerOutput: "67W Max Total",
          Ports: "2x USB-C + 1x USB-A",
        },
        tags: ["charger", "gan", "fast-charging", "anker", "accessories"],
        discountPercent: 5,
        imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_phone_001", "prod_phone_002", "prod_laptop_001"],
        frequentlyBoughtTogetherIds: ["prod_phone_001"],
        upsellProductIds: [],
        alternativeProductIds: [],
        viewCount: 2300,
        salesCount: 310,
      }
    );
    // Monitors, Gifts & Kitchen
    products.push(
      {
        productId: "prod_mon_001",
        merchantId: "merch_apex_001",
        sku: "LG-27GP850",
        name: "LG UltraGear 27-inch QHD Nano IPS 165Hz Monitor",
        category: "Monitors",
        subcategory: "Gaming & Productivity",
        description: "2560x1440 QHD Nano IPS 1ms GtG, 165Hz refresh rate, NVIDIA G-Sync Compatible, HDR400, pivot height-adjustable stand.",
        price: 28999,
        currency: "INR",
        stock: 11,
        availability: "IN_STOCK",
        rating: 4.7,
        reviewCount: 210,
        specifications: {
          Resolution: "2560 x 1440 (QHD 2K)",
          Panel: "Nano IPS 98% DCI-P3",
          RefreshRate: "165Hz",
        },
        tags: ["monitor", "gaming", "qhd", "lg", "ultragear", "productivity"],
        discountPercent: 6,
        imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_laptop_001", "prod_laptop_002", "prod_laptop_004"],
        frequentlyBoughtTogetherIds: ["prod_acc_001"],
        upsellProductIds: [],
        alternativeProductIds: [],
        viewCount: 2800,
        salesCount: 95,
      },
      {
        productId: "prod_gift_001",
        merchantId: "merch_apex_001",
        sku: "KINDLE-PW-16",
        name: "Kindle Paperwhite 16GB (6.8-inch with Adjustable Warm Light)",
        category: "Books",
        subcategory: "E-Readers",
        description: "Glare-free 300 ppi display reads like real paper even in bright sunlight, adjustable warm light, waterproof IPX8, up to 10 weeks battery.",
        price: 13999,
        currency: "INR",
        stock: 18,
        availability: "IN_STOCK",
        rating: 4.8,
        reviewCount: 620,
        specifications: {
          Storage: "16GB",
          Display: "6.8-inch Paperwhite 300 ppi",
        },
        tags: ["books", "kindle", "e-reader", "reading", "gifts"],
        discountPercent: 0,
        imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: [],
        frequentlyBoughtTogetherIds: ["prod_gift_002"],
        upsellProductIds: [],
        alternativeProductIds: [],
        viewCount: 1950,
        salesCount: 140,
      },
      {
        productId: "prod_gift_002",
        merchantId: "merch_apex_001",
        sku: "ART-TAB-10",
        name: "XP-Pen Deco 01 V2 Digital Graphic Drawing Tablet",
        category: "Gifts",
        subcategory: "Creative Arts",
        description: "10x6.25 inch large working area, 8192 levels pressure sensitivity, battery-free stylus, 8 customizable keys, ideal gift for daughter or artist.",
        price: 3499,
        currency: "INR",
        stock: 24,
        availability: "IN_STOCK",
        rating: 4.6,
        reviewCount: 280,
        specifications: {
          ActiveArea: "10 x 6.25 inches",
          PressureLevels: "8192 levels",
        },
        tags: ["drawing", "art", "tablet", "gifts", "daughter", "birthday", "creativity"],
        discountPercent: 10,
        imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_gift_003"],
        frequentlyBoughtTogetherIds: ["prod_gift_003"],
        upsellProductIds: [],
        alternativeProductIds: [],
        viewCount: 2200,
        salesCount: 230,
      },
      {
        productId: "prod_gift_003",
        merchantId: "merch_apex_001",
        sku: "ART-SUP-72",
        name: "Faber-Castell Creative Studio 72-Piece Artist Coloring Set",
        category: "Gifts",
        subcategory: "Art Supplies",
        description: "Premium artist coloring set including 36 watercolor pencils, 24 oil pastels, graphite drawing pencils, blending brushes, in wooden box.",
        price: 1299,
        currency: "INR",
        stock: 30,
        availability: "IN_STOCK",
        rating: 4.8,
        reviewCount: 190,
        specifications: {
          Pieces: "72 high-pigment pieces",
          Box: "Cedar Wood Case",
        },
        tags: ["art", "coloring", "gifts", "birthday", "supplies", "creativity", "daughter"],
        discountPercent: 0,
        imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: ["prod_gift_002"],
        frequentlyBoughtTogetherIds: ["prod_gift_002"],
        upsellProductIds: [],
        alternativeProductIds: [],
        viewCount: 1750,
        salesCount: 260,
      },
      {
        productId: "prod_home_001",
        merchantId: "merch_apex_001",
        sku: "PHIL-AF-41L",
        name: "Philips Digital Air Fryer HD9252 (4.1 Litre)",
        category: "Kitchen",
        subcategory: "Appliances",
        description: "Rapid Air technology with unique starfish design for 90% less fat cooking, digital touch screen with 7 pre-set menus.",
        price: 6999,
        currency: "INR",
        stock: 20,
        availability: "IN_STOCK",
        rating: 4.6,
        reviewCount: 450,
        specifications: {
          Capacity: "4.1 Litre",
          Power: "1400 Watts",
        },
        tags: ["kitchen", "home", "air-fryer", "appliances", "healthy"],
        discountPercent: 12,
        imageUrl: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80",
        compatibleProductIds: [],
        frequentlyBoughtTogetherIds: [],
        upsellProductIds: [],
        alternativeProductIds: [],
        viewCount: 3100,
        salesCount: 340,
      }
    );

    // Upsert products idempotently
    for (const prod of products) {
      await Product.findOneAndUpdate(
        { productId: prod.productId },
        prod,
        { upsert: true }
      );
    }
    console.log(`[SEED] Upserted ${products.length} realistic products across categories.`);

    // 5. Seed Pre-analyzed Revenue Opportunities for Merchant Orchestrator
    const sampleOpportunities = [
      {
        opportunityId: "opp_cross_001",
        merchantId: "merch_apex_001",
        type: "cross_sell",
        title: "Programming Laptop + MX Master 3S Productivity Bundle",
        description: "38% of customers viewing Lenovo IdeaPad and ThinkPad search for high-precision mice.",
        observation: "Customers buying coding laptops frequently browse the Logitech MX Master 3S within 48 hours.",
        suggestedAction: "Present the MX Master 3S as an immediate 1-click add-on with 5% accessory discount upon laptop selection.",
        primaryProductId: "prod_laptop_001",
        relatedProductIds: ["prod_acc_001"],
        suggestedDiscount: 5,
        estimatedRevenueImpact: 42000,
        confidenceScore: 0.92,
        status: "PENDING",
      },
      {
        opportunityId: "opp_cross_002",
        merchantId: "merch_apex_001",
        type: "bundle",
        title: "Daughter's Creative Birthday Combo",
        description: "XP-Pen Drawing Tablet + Faber-Castell 72-Piece Set perfectly fulfills the sub-?5,000 gifting intent.",
        observation: "Parents searching for creative art gifts frequently abandon cart when individual items exceed ?5,000.",
        suggestedAction: "Package XP-Pen Graphic Tablet (?3,499) + Art Set (?1,299) at combo price ?4,499 with free gift wrapping.",
        primaryProductId: "prod_gift_002",
        relatedProductIds: ["prod_gift_003"],
        suggestedDiscount: 6,
        estimatedRevenueImpact: 28500,
        confidenceScore: 0.88,
        status: "PENDING",
      },
      {
        opportunityId: "opp_upsell_001",
        merchantId: "merch_apex_001",
        type: "upsell",
        title: "ThinkPad E14 Upgrade from IdeaPad Slim 5",
        description: "For ?5,000 more, developers gain 8-core Ryzen 7 and military-spec durability.",
        observation: "Customers with budget up to ?70,000 often accept ThinkPad upgrade when developer benefits (keyboard, 1TB SSD) are explained.",
        suggestedAction: "Automate Buyer Agent comparison card showing +?5,000 upgrade value proposition during laptop shopping.",
        primaryProductId: "prod_laptop_001",
        relatedProductIds: ["prod_laptop_002"],
        suggestedDiscount: 0,
        estimatedRevenueImpact: 65000,
        confidenceScore: 0.89,
        status: "PENDING",
      },
    ];

    for (const opp of sampleOpportunities) {
      await RevenueOpportunity.findOneAndUpdate(
        { opportunityId: opp.opportunityId },
        opp,
        { upsert: true }
      );
    }
    console.log(`[SEED] Upserted ${sampleOpportunities.length} AI Revenue Opportunities.`);

    console.log("[SEED] Seeding completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("[SEED ERROR] Seeding failed:", error);
    process.exit(1);
  }
};

seedData();
